[[plugins]] # This is God
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]] # quickrun
repo = 'thinca/vim-quickrun'
hook_add = '''
let g:quickrun_config = get(g:, 'quickrun_config', {})
let g:quickrun_config._ = {
  \ "runner" : 'vimproc',
  \ "runner/vimproc/updatetime" : 60,
  \ "runner/vimproc/read_timeout" : 1000,
  \ 'outputter/buffer/split' : ':rightbelow 8sp',
  \ "outputter/buffer/close_on_empty" : 1,
  \}
'''
depends = ['vimproc']

[[plugins]]
repo = 'Shougo/denite.nvim'

#
# Edit
#

[[plugins]] # Comment out
repo = 'tyru/caw.vim'
hook_add = '''
nmap \c <Plug>(caw:I:toggle)
vmap \c <Plug>(caw:I:toggle)
'''

[[plugins]] # Syntastic
repo = 'scrooloose/syntastic.git'
hook_add = '''
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 0
let g:syntastic_check_on_wq = 0

let g:syntastic_python_checkers = ['flake8', 'mypy']
let g:syntastic_javascript_checkers = ['eslint']
let g:syntastic_go_checkers = ['golint', 'go']
'''

[[plugins]] # Syntastic
repo = 'pmsorhaindo/syntastic-local-eslint.vim'
hook_add = '''
'''

#
# Display
#

[[plugins]] # molokai
repo = 'tomasr/molokai'
hook_add = '''
au MyAutoCmd VimEnter * nested colorscheme molokai
au MyAutoCmd VimEnter * :hi Normal ctermbg=none
set t_Co=256
'''

[[plugins]] # Status bar
repo = 'itchyny/lightline.vim'
hook_add = '''
let g:lightline = {
  \   'colorscheme': 'wombat'
  \ }
'''

[[plugins]] # Indent guide
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
let g:indent_guides_enable_on_vim_startup = 1
au MyAutoCmd VimEnter,Colorscheme * :hi IndentGuidesOdd  ctermbg=233
au MyAutoCmd VimEnter,Colorscheme * :hi IndentGuidesEven ctermbg=234
'''

[[plugins]] # Indent guide
repo = 'airblade/vim-gitgutter'

#
# Language
#

[[plugins]] # Haml
repo  = 'tpope/vim-haml'
on_ft = 'haml'

[[plugins]] # Html5
repo  = 'othree/html5.vim'
on_ft = 'html'

[[plugins]] # Toml
repo  = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]] # Markdown
repo = 'rcmdnk/vim-markdown'
on_ft = ['markdown','mkd']
hook_add = '''
let g:vim_markdown_frontmatter = 1
let g:vim_markdown_math = 1
let g:vim_markdown_folding_disabled = 1
'''

[[plugins]] # Golang
repo = 'fatih/vim-go'
on_ft = 'go'
hook_add = '''
let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_highlight_structs = 1
'''

[[plugins]] # TMUX
repo = 'tmux-plugins/vim-tmux'
on_ft = 'tmux'

[[plugins]] # JSX
repo = 'mxw/vim-jsx'
hook_add = '''
let g:jsx_ext_required = 0
let g:jsx_pragma_required = 0
'''
on_ft = 'javascript'

[[plugins]] # vue
repo = 'posva/vim-vue'
hook_add = '''
autocmd BufNewFile,BufRead *.vue set ft=vue
'''
on_ft = 'vue'

[[plugins]] # memo
repo = 'glidenote/memolist.vim'
hook_add = '''
nnoremap <Leader>mn  :MemoNew<CR>
nnoremap <Leader>ml  :MemoList<CR>
nnoremap <Leader>mg  :MemoGrep<CR>
'''

[[plugins]] # json
repo = 'elzr/vim-json'
hook_add = '''
let g:vim_json_syntax_conceal = 0
'''
