[[plugins]] # echodoc
repo = 'Shougo/echodoc.vim'
hook_add = '''
set cmdheight=2
let g:echodoc_enable_at_startup = 1
'''
on_i = 1

#
# Snippets
#

[[plugins]]
repo = 'Shougo/neosnippet'
hook_source = '''
imap <C-k> <Plug>(neosnippet_expand_or_jump)
smap <C-k> <Plug>(neosnippet_expand_or_jump)
xmap <C-k> <Plug>(neosnippet_expand_target)
if has('conceal')
  set conceallevel=2 concealcursor=niv
endif
'''
on_i = 1
on_ft = ['snippet']
depends = ['neosnippet-snippets']

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]] # Completion
repo = 'Shougo/deoplete.nvim'
hook_add = '''
let g:python_host_prog = $HOME . "/.pyenv/versions/neovim2/bin/python"
let g:python3_host_prog = $HOME . "/.pyenv/versions/neovim3/bin/python"
let g:deoplete#enable_at_startup = 1
let g:deoplete#omni_patterns = {}
inoremap <silent><expr> <Tab> pumvisible() ? "\<C-n>" : deoplete#mappings#manual_complete()
'''
on_i = 1

#
# deoplete sources
#

[[plugins]] # vim
repo = 'Shougo/neco-vim'
on_i = 1

[[plugins]] # jedi
repo = 'zchee/deoplete-jedi'
hook_add = '''
set completeopt-=preview
'''
on_ft = 'python'
on_i = 1

[[plugins]] # javascript
repo = 'carlitux/deoplete-ternjs'
hook_add = '''
'''
on_ft = 'javascript'
on_i = 1

[[plugins]] # go
repo = 'zchee/deoplete-go'
on_ft = 'go'
on_i = 1

[[plugins]] # json
repo = 'Quramy/vison'
on_ft = 'json'
on_i = 1
