[[plugins]] # echodoc
repo = 'Shougo/echodoc.vim'
hook_add = '''
set cmdheight=2
let g:echodoc_enable_at_startup = 1
'''
on_i = 1

[[plugins]] # Completion
repo = 'Shougo/deoplete.nvim'
hook_add = '''
let g:deoplete#enable_at_startup = 1
let g:deoplete#omni_patterns = {}
inoremap <silent><expr> <Tab> pumvisible() ? "\<C-n>" : deoplete#mappings#manual_complete()
'''
on_i = 1

#
# deoplete sources
#

[[plugins]] # vim
repo = 'Shougo/neco-vim'
on_i = 1

[[plugins]] # jedi
repo = 'zchee/deoplete-jedi'
hook_add = '''
let g:python_host_prog = $HOME . "/.pyenv/versions/neovim2/bin/python"
let g:python3_host_prog = $HOME . "/.pyenv/versions/neovim3/bin/python"
set completeopt-=preview
'''
on_ft = 'python'
on_i = 1
