[[plugins]] # This is God
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
if dein#util#_is_windows()
  let cmd = 'tools\\update-dll-mingw'
elseif dein#util#_is_cygwin()
  let cmd = 'make -f make_cygwin.mak'
elseif executable('gmake')
  let cmd = 'gmake'
else
  let cmd = 'make'
endif
let g:dein#plugin.build = cmd
'''

[[plugins]] # quickrun
repo = 'thinca/vim-quickrun'
hook_add = '''
let g:quickrun_config = get(g:, 'quickrun_config', {})
let g:quickrun_config._ = {
  \ "runner" : 'vimproc',
  \ "runner/vimproc/updatetime" : 60,
  \ "runner/vimproc/read_timeout" : 1000,
  \ 'outputter/buffer/split' : ':rightbelow 8sp',
  \ "outputter/buffer/close_on_empty" : 1,
  \}
let g:quickrun_config.python = {
\ "cmdopt" : "-u"
\}
'''
depends = ['vimproc']

[[plugins]]
repo = 'Shougo/denite.nvim'

#
# Edit
#

[[plugins]] # Comment out
repo = 'tyru/caw.vim'
hook_add = '''
nmap \c <Plug>(caw:I:toggle)
vmap \c <Plug>(caw:I:toggle)
'''

[[plugins]] # Syntastic
repo = 'scrooloose/syntastic.git'
hook_add = '''
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 0
let g:syntastic_check_on_wq = 0

let g:syntastic_python_checkers = ['flake8']
let g:syntastic_javascript_checkers = ['eslint']
'''

[[plugins]] # Syntastic
repo = 'pmsorhaindo/syntastic-local-eslint.vim'
hook_add = '''
'''

[[plugins]] # Unite
repo = 'Shougo/unite.vim'
hook_add = '''
'''

#
# Display
#

[[plugins]] # molokai
repo = 'tomasr/molokai'
hook_add = '''
au MyAutoCmd VimEnter * nested colorscheme molokai
au MyAutoCmd VimEnter * :hi Normal ctermbg=none
set t_Co=256
'''

[[plugins]] # Status bar
repo = 'itchyny/lightline.vim'
hook_add = '''
let g:lightline = {
  \   'colorscheme': 'wombat'
  \ }
'''

[[plugins]] # Indent guide
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
let g:indent_guides_enable_on_vim_startup = 1
au MyAutoCmd VimEnter,Colorscheme * :hi IndentGuidesOdd  ctermbg=233
au MyAutoCmd VimEnter,Colorscheme * :hi IndentGuidesEven ctermbg=234
'''

[[plugins]] # Indent guide
repo = 'airblade/vim-gitgutter'

#
# Language
#

[[plugins]] # Haml
repo  = 'tpope/vim-haml'
on_ft = 'haml'

[[plugins]] # Html5
repo  = 'othree/html5.vim'
on_ft = 'html'

[[plugins]] # Toml
repo  = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]] # Markdown
repo = 'rcmdnk/vim-markdown'
on_ft = ['markdown','mkd']
hook_add = '''
let g:vim_markdown_frontmatter = 1
let g:vim_markdown_math = 1
'''

[[plugins]] # Golang
repo = 'fatih/vim-go'
on_ft = 'go'

[[plugins]] # TMUX
repo = 'tmux-plugins/vim-tmux'
on_ft = 'tmux'

[[plugins]] # Japanese doc
repo = 'vim-jp/vimdoc-ja'
on_ft = 'help'

[[plugins]] # JSX
repo = 'mxw/vim-jsx'
hook_add = '''
let g:jsx_ext_required = 0
let g:jsx_pragma_required = 0
'''
on_ft = 'javascript'

[[plugins]] # vue
repo = 'posva/vim-vue'
hook_add = '''
autocmd BufNewFile,BufRead *.vue set ft=vue
'''
on_ft = 'vue'
