- name: Download latest peco
  get_url: url=https://github.com/peco/peco/releases/download/v.0.4.2/peco_linux_amd64.tar.gz dest=/tmp/peco_linux_amd64.tar.gz

- name: Extract peco
  unarchive: src=/tmp/peco_linux_amd64.tar.gz dest=/tmp/

- name: Copy to ~/local/bin/
  copy: src=/tmp/peco_linux_amd64/peco dest={{ my_bin_path }} mode=0755
